name: SSH to EC2 Instance

on:
  push:
    branches:
      - ivan_devops

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ vars.key_compras }}
      REMOTE_USER: ec2-user
      REMOTE_HOST: ${{ vars.AWS_DEV_HOST_COMPRAS }}

    steps:
    - name: install packages
      uses: appleboy/ssh-action@0.1.10
      with:
        host: ${{ env.REMOTE_HOST }}
        username: ${{ env.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo yum update -y
