name: SSH to EC2 Instance

on:
  push:
    branches:
      - ivan_devops

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ vars.key_compras }}
      REMOTE_USER: ec2-user
      REMOTE_HOST: ${{ vars.AWS_DEV_HOST_COMPRAS }}

    steps:
    - name: ssh-pipeline
      uses: cross-the-world/ssh-pipeline@v1.2.0
      with:
        # ssh remote host
        host: ${{ env.REMOTE_HOST }}
        # ssh remote user
        user: ${{ env.REMOTE_USER }}
        # content of ssh private key. ex raw content of ~/.ssh/id_rsa
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo yum update -y