name: SSH EC2
on:
    push:
      branches:
        - santiagocenturion_pagos
  
  jobs:
    deploy:
      runs-on: ubuntu-latest
  
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PEM_FILE_PAGOS }}
        REMOTE_USER: ec2-user
        REMOTE_HOST: ${{ secrets.DIRECTION_IP_AWS_PAGOS }}
  
      steps:
      - name: checkout
        uses: actions/checkout@v4
  
      - name: eliminar carpeta en caso de existir
        uses: appleboy/ssh-action@master
        with:
           host: ${{env.REMOTE_HOST}}
           username: ${{env.REMOTE_USER}}
           key: ${{env.SSH_PRIVATE_KEY }}
           script: sudo rm -rf /opt/pagos || true
  
      - name: Crear la carpeta /opt/pagos
        uses: appleboy/ssh-action@master
        with:
           host: ${{env.REMOTE_HOST}}
           username: ${{env.REMOTE_USER}}
           key: ${{env.SSH_PRIVATE_KEY }}
           script: |
            sudo mkdir -p /opt/pagos
  
      - name: Actualizar paquetes
        uses: appleboy/ssh-action@master
        with:
           host: ${{env.REMOTE_HOST}}
           username: ${{env.REMOTE_USER}}
           key: ${{env.SSH_PRIVATE_KEY }}
           script: |
            sudo yum update
  
      - name: Instalar Node.js, npm y Git
        uses: appleboy/ssh-action@master
        with:
           host: ${{env.REMOTE_HOST}}
           username: ${{env.REMOTE_USER}}
           key: ${{env.SSH_PRIVATE_KEY }}
           script: |
            sudo yum update
            sudo yum install -y nodejs npm git
  
      - name: Clonar repositorio
        uses: appleboy/ssh-action@master
        with:
           host: ${{env.REMOTE_HOST}}
           username: ${{env.REMOTE_USER}}
           key: ${{env.SSH_PRIVATE_KEY }}
           script: |
            sudo git clone -b pagos https://github.com/alkemyTech/UMSA-Softtek-DevOps-Base.git /opt/pagos
  
  
      - name: Instalar express
        uses: appleboy/ssh-action@master
        with:
           host: ${{env.REMOTE_HOST}}
           username: ${{env.REMOTE_USER}}
           key: ${{env.SSH_PRIVATE_KEY }}
           script: |
            cd /opt/pagos
            sudo npm install express --save
  
      - name: Instalar pm2
        uses: appleboy/ssh-action@master
        with:
           host: ${{env.REMOTE_HOST}}
           username: ${{env.REMOTE_USER}}
           key: ${{env.SSH_PRIVATE_KEY }}
           script: |
            cd /opt/pagos
            sudo npm install -g pm2
  
      - name: Detener servicio Node con PM2 si est치 en ejecuci칩n
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/pagos
            sudo pm2 stop app.js || true  
  
  
      - name: Iniciar servicio Node con PM2
        uses: appleboy/ssh-action@master
        with:
           host: ${{env.REMOTE_HOST}}
           username: ${{env.REMOTE_USER}}
           key: ${{env.SSH_PRIVATE_KEY }}
           script: |
            cd /opt/pagos
            sudo pm2 start app.js
      
      - name: Chequear si la aplicaci칩n est치 corriendo
        uses: appleboy/ssh-action@master
        with:
           host: ${{env.REMOTE_HOST}}
           username: ${{env.REMOTE_USER}}
           key: ${{env.SSH_PRIVATE_KEY }}
           script: |
            sudo pm2 status myapp
  
      - name: Mostrar informacion de la pagina
        uses: appleboy/ssh-action@master
        with:
           host: ${{env.REMOTE_HOST}}
           username: ${{env.REMOTE_USER}}
           key: ${{env.SSH_PRIVATE_KEY }}
           script: |
            sudo curl localhost:3000