name: SSH to EC2 Instance and Remove Directory

on:
  push:
    branches:
      - ivan_devops

jobs:
  Deploy:
    name: ssh_to_ec2_and_remove_dir
    runs-on: ubuntu-latest



    steps:
    - uses: actions/checkout@v3
    - name: SSH into EC2 Instance and Remove Directory
      env:
          SSH_PRIVATE_KEY: ${{ secrets.PEM_FILE_COMPRAS }}
          REMOTE_USER: ec2-user
          REMOTE_HOST: ${{ secrets.AWS_DEV_HOST_COMPRAS }}
      run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i SSH_PRIVATE_KEY ${REMOTE_USER}@${REMOTE_HOST}