name: Print Message

on:
  push:
    branches:
      - ivan_devops  # Cambia "main" por el nombre de tu rama principal si es diferente

jobs:
  print_message:
    runs-on: ubuntu-latest
    steps:
    - name: Print a message
      run: echo "Working!" ${{ env.REMOTE_HOST }}
