name: proyecto final

on:
  push:
    branches:
      - ivan_devops

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ vars.key_compras }}
      REMOTE_USER: ec2-user
      REMOTE_HOST: ${{ vars.AWS_DEV_HOST_COMPRAS }}

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Connect and write a message
      uses: appleboy/ssh-action@master
      with:
         host: ${{env.REMOTE_HOST}}
         username: ${{env.REMOTE_USER}}
         key: ${{env.SSH_PRIVATE_KEY }}
         script: sudo rm -rf /opt/compras || true

    - name: Crear la carpeta /opt/compras
      uses: appleboy/ssh-action@master
      with:
         host: ${{env.REMOTE_HOST}}
         username: ${{env.REMOTE_USER}}
         key: ${{env.SSH_PRIVATE_KEY }}
         script: |
          sudo mkdir -p /opt/compras