name: SSH to EC2 Instance and Remove Directory

on:
  push:
    branches:
      - ivan_devops

jobs:
  ssh_to_ec2_and_remove_dir:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: "MIIEowIBAAKCAQEArB72WXnXZzFy9LlSQ6rc8YIzzUrSu+Nv1b6vCbCoQfQbbird7lDjJeMQz/myxLb2HWX8wNTMSTM/eim8PWvEY1/OHN5gY2b4YJkSHaxyv86mdXI6yn585lghV1eS71zRk8hEiGmVGSG3Iegjg4iDccdQbg+fWkNBmoCPEA6DSmraZHq89REl2Fp7CjxRXSADANVqPQ32FBbjEU49hJ7vFI5nRuWLK67EBqkVo0+mVH8IU6xkbRZtYij2o7ic8e+UW50NZ2VLzTMbG2vNIE1iH1tGlmLV0dtkLqjtzu8CUp+cgf0YcKeYvJpsCNDEK3TqgshK/CZVkxMhr6ExRdFLswIDAQABAoIBAB+Ar0AjL8ygXVTzUl42OKgvV4HcjwN6li597xWL8s/XeOnKCMKkpV5618no/tJIVnV9BCzbBeTj71tRpjVrsw8pKtVX0jZ/UziC67Dorjvy+76FQMNtMTkLqlaNHcSXrXgp8HkzMenepOEc1tstMjmx7EOoslbX9nrrysN6lIcbB/a5zHwnDuAwPLH+qvS6a7gIe8I2PVCgHiB9CJ88ORIywngdiPbPqeMr+9iODfyH9njVEx7vL+mUrJUKt2+EVc2YHNcddbWun+ygsXqqiepzTMvQvRJcVL3EtSmVvswHgI7Ao439+4LIRSlOec8W8finKoCI9ozqLZBra7ArhbECgYEA8TF7mCx5Rn3T9alzVtUqIexS8ZgKxetmFcP35OJl+RjX8WgNTc3K6xfah8LO9ReiER6DluDc002nhVUWufhdL3lFXBKDYeXfLixM43l7hRKL+hqHmPgWFIXfXFd5rQWgN8c6PTOrhUc3Ti5D3iE9uXYfptOAiZYRvlNUrBej6PsCgYEAtq/14Gzqs3f/JlYQQ0HHeL/nndRJGBEDS4HQfET7S/DU8bja/bz6Q166bZiU3trcWL75zu9PdadkQ6mFxMrAfIhogEhDR9lc5czlXyz0jbMq9VdOnb4Eav8g4Xju04t7NWMVRgVw1B6tqoz6qMEaNSJnTzOmeltdfa8g34JpGqkCgYBbRT5f93RtGHB9JgJfeYrYC3XXtpFdFBctZVsJYiL0gFI3KAjgyF9hV0V62l02ohrSH5nsHmtyCpC6A9j1xuZ8cIeur9LH2RT7hAgUjIQRd1NA8YkeecLhQUekyfVhZB+c++cuAb+GT8y96QQFqs6QwAJ6Ps8FQaS1QRNpjAiawQKBgQCYATzyaW23uoaAXWfWrmrMm9CaUEIpVi6Jqw/P9o2pmE92eTstmQoa+DziZ+ymqTBiXzT368MPwCH68pitL46Nj+pzoqzooYFca+oGER/Cr2t1DBoLwklmxbWUJc2CEzKHL1RKGMjSllwl5nvB4jpuL5wKGI3SjSbzJr6Req79UQKBgCew6833AxK0mnUGLjKIEVO82kFMb/0VyuV2VS/OtzcNVwqPHB/YhafQCy3r6qSjh1cPYX4K4GFlH9aDP5+7ZNatlU9KpwzGlDLP9QzA86Hg4KXwa8nbjdn0GRqMn0aZercx089IuX4YoZlpg7g4BB1Qxpl6BbVJAoC1AtT2cFHU"
      REMOTE_USER: ec2-user
      REMOTE_HOST: "3.83.175.110"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into EC2 Instance and Remove Directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.REMOTE_HOST }}
        username: ${{ env.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo rm -rf /opt/montoto || { echo "Directory removal failed"; exit 1; }
