name: proyecto final

on:
  push:
    branches:
      - ivan_devops

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ vars.key_compras }}
      REMOTE_USER: ec2-user
      REMOTE_HOST: ${{ vars.AWS_DEV_HOST_COMPRAS }}

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: eliminar carpeta en caso de existir
      uses: appleboy/ssh-action@master
      with:
         host: ${{env.REMOTE_HOST}}
         username: ${{env.REMOTE_USER}}
         key: ${{env.SSH_PRIVATE_KEY }}
         script: sudo rm -rf /opt/compras || true

    - name: Crear la carpeta /opt/compras
      uses: appleboy/ssh-action@master
      with:
         host: ${{env.REMOTE_HOST}}
         username: ${{env.REMOTE_USER}}
         key: ${{env.SSH_PRIVATE_KEY }}
         script: |
          sudo mkdir -p /opt/compras

    - name: Actualizar paquetes
      uses: appleboy/ssh-action@master
      with:
         host: ${{env.REMOTE_HOST}}
         username: ${{env.REMOTE_USER}}
         key: ${{env.SSH_PRIVATE_KEY }}
         script: |
          sudo yum update

    - name: Instalar Node.js, npm y Git
      uses: appleboy/ssh-action@master
      with:
         host: ${{env.REMOTE_HOST}}
         username: ${{env.REMOTE_USER}}
         key: ${{env.SSH_PRIVATE_KEY }}
         script: |
          sudo yum update
          sudo yum install -y nodejs npm git

    - name: Clonar repositorio
      uses: appleboy/ssh-action@master
      with:
         host: ${{env.REMOTE_HOST}}
         username: ${{env.REMOTE_USER}}
         key: ${{env.SSH_PRIVATE_KEY }}
         script: |
          sudo git clone -b compras https://github.com/alkemyTech/UMSA-Softtek-DevOps-Base.git /opt/compras


    - name: Instalar paquetes NPM
      uses: appleboy/ssh-action@master
      with:
         host: ${{env.REMOTE_HOST}}
         username: ${{env.REMOTE_USER}}
         key: ${{env.SSH_PRIVATE_KEY }}
         script: |
          cd /opt/compras
          sudo npm install pm2 express --save

    - name: Iniciar servicio Node con PM2
      uses: appleboy/ssh-action@master
      with:
         host: ${{env.REMOTE_HOST}}
         username: ${{env.REMOTE_USER}}
         key: ${{env.SSH_PRIVATE_KEY }}
         script: |
          cd /opt/compras
          sudo pm2 start app.js
    
    - name: Chequear si la aplicación está corriendo
      uses: appleboy/ssh-action@master
      with:
         host: ${{env.REMOTE_HOST}}
         username: ${{env.REMOTE_USER}}
         key: ${{env.SSH_PRIVATE_KEY }}
         script: |
          sudo pm2 status myapp

    - name: MOstrar informacion de la pagina
      uses: appleboy/ssh-action@master
      with:
         host: ${{env.REMOTE_HOST}}
         username: ${{env.REMOTE_USER}}
         key: ${{env.SSH_PRIVATE_KEY }}
         script: |
          sudo curl ${{env.REMOTE_HOST}}:3000