name: Deploy App Cobranzas

# Trigger.
on:
  push:
    branches:
      - cobranzas_qa_am

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Variables de entorno.
    env:
      SSH_PRIVATE_KEY: ${{ secrets.PEM_COBRANZAS_QA }}
      REMOTE_USER: ec2-user
      REMOTE_HOST: ${{ vars.IP_COBRANZAS_QA }}
      GITHUB_TOKEN: ${{ secrets.TOKEN_GH_AM }}
      #Conexion dockerhub
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME_AM }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD_AM }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN_AM }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install packages Nodejs Npm Git
      - name: Install Packages
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            sudo yum update -y
            sudo yum install nodejs npm git -y

      # Create a Directory
      - name: Create a Directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            sudo rm -rf /opt/cobranzas || true
            cd /opt
            sudo mkdir -p cobranzas

      # Execute git clone.
      - name: Clone repository
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/cobranzas
            sudo git clone -b cobranzas_qa_am https://github.com/alkemyTech/UMSA-DevOps-T1.git /opt/cobranzas

      # Install npm packages express pm2.
      - name: Install npm packages
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/cobranzas
            sudo npm install -g express pm2

      # Start service
      - name: Start Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/cobranzas
            sudo pm2 delete app.js || true
            sudo pm2 start app.js --name 'app.js'

      # Check if app is running
      - name: Check if app is running
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            if sudo pm2 ls | grep -q 'app.js'; then
              echo "El servicio app.js est치 en ejecuci칩n."
            else
              echo "El servicio app.js no est치 en ejecuci칩n."
              exit 1
            fi

      - name: Generar Imagen Docker
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: Dockerfile
          push: false
          tags: ${{ env.DOCKERHUB_USERNAME }}/cobranzas_qa:latest
      
      - name: Iniciar sesion en docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
      
      - name: Subir a DockerHub
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/cobranzas_qa:latest
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Check if app is running
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            sudo docker stop cobranzas_qa || true
            sudo docker rm cobranzas_qa || true
            sudo docker pull ${{ env.DOCKERHUB_USERNAME }}/cobranzas_qa:latest
            sudo docker run -d --name cobranzas_qa -p 8080:8080 ${{ env.DOCKERHUB_USERNAME }}/cobranzas_qa:latest

  
